name: Build and Export ARM64 Docker Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: 构建 ARM64 的 Docker 镜像
      - name: Build ARM64 Docker Image
        run: |
          mkdir -p output
          docker buildx build \
            --platform linux/arm64 \
            --file Dockerfile \
            --output type=docker,dest=output/arm64-image.tar \
            -t cloud-clipboard:arm64 .

      # Step 4: 等待文件释放
      - name: Wait for File Release
        run: sleep 5

      # Step 5: 压缩导出的镜像文件
      - name: Compress Docker Image
        run: |
          tar -czf arm64-image.tar.gz -C output arm64-image.tar
          echo "TAR_PATH=$PWD/arm64-image.tar.gz" >> $GITHUB_ENV

      # Step 6: 上传镜像文件为 Artifact
      - name: Upload ARM64 Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-arm64
          path: ${{ env.TAR_PATH }}