name: Docker Build for Multiple Architectures

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-multi-arch
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for amd64 and arm64
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile --tag cloud-clipboard:amd64 --tag cloud-clipboard:arm64 .

      - name: Save Docker images as tar files for amd64 and arm64
        run: |
          docker save -o cloud-clipboard-amd64.tar cloud-clipboard:amd64
          docker save -o cloud-clipboard-arm64.tar cloud-clipboard:arm64

      - name: Upload Docker images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cloud-clipboard-images
          path: |
            cloud-clipboard-amd64.tar
            cloud-clipboard-arm64.tar
